### PR TITLE
Use bazel to build docker image

### PR DESCRIPTION
**Pull request by zhenghuiwang**
Update Dockerfile to build image with Bazel.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/metadata/36)

### CODE REVIEW

**Comment by neuromage** [comment]
/lgtm

Thanks @zhenghuiwang 

Btw, do you have cycles to look into the OSPO release process for this image? I can sync with you offline on how to do this (I hacked a tool to help a bit with this).

**Comment by zhenghuiwang** [comment]
Thanks for the review! We can sync on the OSPO release offline.

/approve

**Pull request merged**
