### PR TITLE
ListArtifacts should return an empty list if no artifacts exists

### PR DESCRIPTION
**Pull request by zhenghuiwang**
**Which issue(s) this PR fixes** 
Fixes https://github.com/kubeflow/metadata/issues/63

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/metadata/64)

### CODE REVIEW

**Comment by prodonjs** [comment]
Doesn't look like I can approve since I'm not an owner.

**Comment by zhenghuiwang** [comment]
Thanks for the review! Merging it myself.

/approve

**Pull request merged**
