### PR TITLE
Owner Updates to add Kwasi / AP and remove Riley

### PR DESCRIPTION
**Pull request by avdaredevil**
## About
- Added AP, Kwasi (Since we're working on MLMD and foreseeable KFP tasks)
- Removed Riley (No longer in the project)

**Release note**:

NONE

### Meta
/area front-end
/area metadata
/priority p1
/assign @avdaredevil
/cc @prodonjs @kwasi

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/metadata/143)

### CODE REVIEW

**Comment by avdaredevil** [comment]
@Kwasi Can you work on getting this done?

**Comment by kwasi** [comment]
@avdaredevil Thanks for taking care of this. I should be part of the org now. 

/verify-owners

**Comment by avdaredevil** [comment]
Opening, made a mistake and cleaned an active branch

**Pull request merged**
