### PR TITLE
MLMD SDK Notebook spelling nits

### PR DESCRIPTION
**Pull request by avdaredevil**
## About
A few quick spelling nits on the demo notebook for MLMD SDK.

### Meta
/area metadata
/area front-end
/priority p1
/assign @avdaredevil
/cc @kwasi @zhenghuiwang

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/metadata/186)

### CODE REVIEW

**Comment by zhenghuiwang** [comment]
The presubmit test fails because of the failure of installing python3.6 on the testing worker. I will make a PR to fix it.

**Comment by zhenghuiwang** [comment]
@avdaredevil could you rebase this PR? The problematic test has been fixed.

**Comment by avdaredevil** [comment]
@zhenghuiwang done! PTAL :)

**Pull request merged**
