### PR TITLE
Kubeflow Metadata UI init

### PR DESCRIPTION
**Pull request by rileyjbauer**
**What this PR does / why we need it**:
Bootstraps the Kubeflow metadata UI providing a simple Artifact list page and model info page.

**Special notes for your reviewer**:
Lots of credit to @prodonjs for all the work getting the pages set up and sorting out various API issues.
**Release note**:

```release-note
Adds a simple artifact viewing UI
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/metadata/59)

### CODE REVIEW

**Comment by prodonjs** [comment]
@rileyjbauer Somehow it looks like the compiled JS from the `build` folder got into this before the build folder was added to the ignore file (9fa88f5f16187e4b9f9272b35c92e9fdbd1bf98a). Can we make sure those are excluded?

**Comment by rileyjbauer** [comment]
Good call, I've removed those files

**Comment by zhenghuiwang** [comment]
@rileyjbauer Can you add `frontend/OWNERS` file with you and @prodonjs as approvers? so that you two can review and merge PRs for all the UI work.

**Comment by rileyjbauer** [comment]
@zhenghuiwang Yes, good call. Added an OWNERS file

**Comment by prodonjs** [comment]
@rileyjbauer - Anything else we want to include in this first change? If not, can we get @zhenghuiwang to approve this today so we can work forward from this set of changes.

**Comment by rileyjbauer** [comment]
@prodonjs Yes, it should be good to merge this PR. Anything else can be done in follow-ups

**Pull request merged**
