### PR TITLE
Fix ArtifactType/ExecutionType listing

### PR DESCRIPTION
**Pull request by neuromage**
Also remove unused mocks.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/metadata/86)

### CODE REVIEW

**Comment by zhenghuiwang** [comment]
/lgtm

Thanks for the fixes!

**Comment by neuromage** [comment]
@zhenghuiwang how do I see the test logs? I can't get anything from the `Details` links strangely.

**Comment by zhenghuiwang** [comment]
I don't think the presubmit job got started.

/approve

/retest

**Comment by neuromage** [comment]
Thanks @zhenghuiwang. The latest try started but errored out with this error below. Looks like a 404 error for this swagger.json file. Would you understand what's going on here? 
```
INFO|2019-07-10T21:19:52|/src/kubeflow/testing/py/kubeflow/testing/util.py|71| level=error msg="find objects: Received status code '404' when trying to retrieve OpenAPI schema for cluster version 'v0.3.1' from URL 'https://raw.githubusercontent.com/kubernetes/kubernetes/v0.3.1/api/openapi-spec/swagger.json'"
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 417, in <module>
    final_result = main()
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 407, in main
    return run(args, file_handler)
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 273, in run
    util.run([ks_cmd, "show", env, "-c", w.component], cwd=w.app_dir)
  File "/src/kubeflow/testing/py/kubeflow/testing/util.py", line 87, in run
    " ".join(command), process.returncode), "\n".join(output))
subprocess.CalledProcessError: Command 'cmd: ks show kubeflow-metadata-presubmit-unittests-86-0377d0a-2832-8bcf -c workflows exited with code 1' returned non-zero exit status 1
```

**Pull request merged**
