### PR TITLE
Add MySql password flag

### PR DESCRIPTION
**Pull request by zhenghuiwang**
Tested it locally.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/metadata/42)

### CODE REVIEW

**Comment by neuromage** [comment]
/lgtm

How is the password set initially? What does `%password%` get substituted with?

**Comment by zhenghuiwang** [comment]
> How is the password set initially? What does `%password%` get substituted with?

In production, the mysql container and metadata server container will share the same [secret](https://kubernetes.io/docs/concepts/configuration/secret/) when starting both services.

**Comment by neuromage** [comment]
> > How is the password set initially? What does `%password%` get substituted with?
> 
> In production, the mysql container and metadata server container will share the same [secret](https://kubernetes.io/docs/concepts/configuration/secret/) when starting both services.

Is there a connection between secrets and the `%password%` substitution? Sorry if it's obvious, but can you explain how this would work to me?

**Comment by zhenghuiwang** [comment]
> Is there a connection between secrets and the `%password%` substitution? Sorry if it's obvious, but can you explain how this would work to me?

I should have been more specific: the k8s secret is populated to container as the env variable and you can set the cmd flag like this:
https://github.com/kubeflow/manifests/blob/master/metadata/base/metadata-deployment.yaml#L28

**Pull request merged**
