### PR TITLE
Register predefined execution type

### PR DESCRIPTION
**Pull request by zhenghuiwang**
This PR registers the predefined execution type during server start.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/metadata/66)

### CODE REVIEW

**Comment by zhenghuiwang** [comment]
It is ready for your review.
/assign @neuromage

**Comment by neuromage** [comment]
@zhenghuiwang what's the predefined execution type? Is this for notebook executions?

**Comment by zhenghuiwang** [comment]
> @zhenghuiwang what's the predefined execution type? Is this for notebook executions?

Yes, that is the execution type for notebook CUJ, defined [here](https://github.com/kubeflow/metadata/blob/master/schema/alpha/docs/execution.md)

**Pull request merged**
