### PR TITLE
Use papermill to exec Notebook

### PR DESCRIPTION
**Pull request by zhenghuiwang**
Parameterize demo notebook for python SDK with papermill for easy testing.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/metadata/190)

### CODE REVIEW

**Comment by jinchihe** [comment]
Hey @zhenghuiwang Why not use pytest to execute `papermill.execute_notebook` function to test that as below, may be more simple. :-)

https://github.com/kubeflow/examples/blob/0d49548b3a4e4c1511b14272ae7d1b0b86e88612/xgboost_synthetic/testing/execute_notebook.py#L17

**Comment by zhenghuiwang** [comment]
> Hey @zhenghuiwang Why not use pytest to execute `papermill.execute_notebook` function to test that as below, may be more simple. :-)
> 
> https://github.com/kubeflow/examples/blob/0d49548b3a4e4c1511b14272ae7d1b0b86e88612/xgboost_synthetic/testing/execute_notebook.py#L17

Thanks! I guess pytest is easier to run as part of python tests instead of bash scripts. I made the change to use python API of papermill.

**Comment by zhenghuiwang** [comment]
@jinchihe could you take anther look? Thanks

**Comment by jinchihe** [comment]
That's great! @zhenghuiwang 

/lgtm

**Comment by zhenghuiwang** [comment]
Thanks

/approve

**Pull request merged**
