### PR TITLE
update some logs

### LINKED ISSUE #94: Improve the warning log
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
When I run the server, I got following warning that may bring confusion to user :

E0711 01:19:33.022712    9859 register.go:68] Ignored unknown type "workspace" in "http://github.com/kubeflow/metadata/schema/alpha/containers/workspace.json"
W0711 01:19:33.022849    9859 register.go:49] schema misses 'kind', 'apiversion', or 'namespace'. schema $id = http://github.com/kubeflow/metadata/schema/alpha/entity.json: property "namespace" is not constant in http://github.com/kubeflow/metadata/schema/alpha/entity.json, SchemaJSON &{ID: Title: Description:namepace of the entity type Version: Default:<nil> ReadOnly:false Example:<nil> Format: Type:string Ref:<nil> Schema:<nil> Definitions:map[] MultipleOf:0 Maximum:0 ExclusiveMaximum:false Minimum:0 ExclusiveMinimum:false MinLength:0 MaxLength:0 Pattern: MinProperties:0 MaxProperties:0 Required:[] Properties:map[] Dependencies:map[] AdditionalProperties:<nil> PatternProperties:map[] Items:<nil> MinItems:0 MaxItems:0 UniqueItems:false AdditionalItems:<nil> Enum:[] Constant: OneOf:[] AnyOf:[] AllOf:[] Not:<nil> Links:[]}
W0711 01:19:33.025361    9859 register.go:49] schema misses 'kind', 'apiversion', or 'namespace'. schema $id = http://github.com/kubeflow/metadata/schema/alpha/artifacts/artifact.json: property "namespace" is not constant in http://github.com/kubeflow/metadata/schema/alpha/artifacts/artifact.json, SchemaJSON &{ID: Title: Description:namepace of the entity type Version: Default:<nil> ReadOnly:false Example:<nil> Format: Type:string Ref:<nil> Schema:<nil> Definitions:map[] MultipleOf:0 Maximum:0 ExclusiveMaximum:false Minimum:0 ExclusiveMinimum:false MinLength:0 MaxLength:0 Pattern: MinProperties:0 MaxProperties:0 Required:[] Properties:map[] Dependencies:map[] AdditionalProperties:<nil> PatternProperties:map[] Items:<nil> MinItems:0 MaxItems:0 UniqueItems:false AdditionalItems:<nil> Enum:[] Constant: OneOf:[] AnyOf:[] AllOf:[] Not:<nil> Links:[]}
W0711 01:19:33.025404    9859 register.go:49] schema misses 'kind', 'apiversion', or 'namespace'. schema $id = http://github.com/kubeflow/metadata/schema/alpha/artifacts/executable.json: property "namespace" is not constant in http://github.com/kubeflow/metadata/schema/alpha/artifacts/executable.json, SchemaJSON &{ID: Title: Description:namepace of the entity type Version: Default:<nil> ReadOnly:false Example:<nil> Format: Type:string Ref:<nil> Schema:<nil> Definitions:map[] MultipleOf:0 Maximum:0 ExclusiveMaximum:false Minimum:0 ExclusiveMinimum:false MinLength:0 MaxLength:0 Pattern: MinProperties:0 MaxProperties:0 Required:[] Properties:map[] Dependencies:map[] AdditionalProperties:<nil> PatternProperties:map[] Items:<nil> MinItems:0 MaxItems:0 UniqueItems:false AdditionalItems:<nil> Enum:[] Constant: OneOf:[] AnyOf:[] AllOf:[] Not:<nil> Links:[]}

**What did you expect to happen:**
Improve the log to make the warning more clear.

### PR DESCRIPTION
**Pull request by dreamryx**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #94

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/metadata/92)

### CODE REVIEW

**Comment by zhenghuiwang** [comment]
@dreamryx  you may need to rebase in order to pass the tests. thanks

**Comment by dreamryx** [comment]
> @dreamryx you may need to rebase in order to pass the tests. thanks

OK. Thanks! :)

**Pull request merged**
