### PR TITLE
Update swagger generation script to avoid duplicated HTTP path

### LINKED ISSUE #55: Swagger client generation from service specification doesn't generate all methods
/kind bug

**What steps did you take and what happened:**
Ran the following command to generate a Typescript client library from the Metadata service specification using version [2.4.5](https://github.com/swagger-api/swagger-codegen/releases/tag/v2.4.5)
`java -jar swagger-codegen-cli.jar generate -i ../api/service.swagger.json -l typescript-fetch -o ./src/apis/service -c ./swagger-config.json`

**What did you expect to happen:**
Client library with generated methods for each of the following operations to be defined:
```
CreateArtifact,
CreateArtifactType,
CreateExecution,
CreateExecutionType,
DeleteArtifact,
DeleteArtifactType,
DeleteExecution,
DeleteExecutionType,
GetArtifact,
GetArtifactType,
GetExecution,
GetExecutionType,
ListArtifacts,
ListArtifacts2,
ListArtifactTypes,
ListExecutions,
ListExecutions2,
ListExecutionTypes
```

The actual methods created were as follows:
```
createArtifact
createArtifactType
createExecution
createExecutionType
deleteExecutionType
getExecutionType
listArtifactTypes
listArtifacts
listArtifacts2
listExecutionTypes
listExecutions
listExecutions2
```
The following methods were not generated:
```
DeleteArtifact,
DeleteArtifactType,
DeleteExecution,
GetArtifact,
GetArtifactType,
GetExecution
```

**Anything else you would like to add:**
Running `java -jar swagger-codegen-cli.jar validate -i ../api/api.swagger.json` shows no errors. However, pasting the definition into https://editor.swagger.io/ shows the following error message, which seems to indicate an issue with multiple paths of the form `/api/v1alpha1/{name}`
Screenshot from 2019-06-17 10-29-51

**Environment:**
Using `api/service.swagger.json` from master.
**swagger-code-cli** [2.4.5](https://github.com/swagger-api/swagger-codegen/releases/tag/v2.4.5)

### PR DESCRIPTION
**Pull request by zhenghuiwang**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
- Fixes #55 to avoid HTTP path overlap.

- Reduce the assumption of #maximum type stored in the database.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/metadata/58)

### CODE REVIEW

**Comment by zhenghuiwang** [comment]
/assign @prodonjs 

This generates all methods for python client from swagger.

**Comment by zhenghuiwang** [comment]
/hold cancel

Ready for review!

I've updated the script to generate swagger http path like `/api/v1/execution_types/{name}/execution/{id}`, which enable the right code gen for python client `getExectuion` and `getArtifact`.

I don't find good way to automate this, but it is working now.

**Comment by prodonjs** [comment]
Haha wow those are some awesomely hacky sed scripts but they get the job done! Client library generation seems to work properly with the newly formatted file.

**Comment by zhenghuiwang** [comment]
@prodonjs Can you `/lgtm` this pr so that I can merge it?

**Pull request merged**
