### PR TITLE
Fix Yaml formatting

### PR DESCRIPTION
**Pull request by abhi-g**
OWNERS file is not functional without the Yaml fix.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/metadata/1)

### CODE REVIEW

**Comment by neuromage** [comment]
@abhi-g should we add yourself and @jlewi as owners here too? 
/lgtm
/approve

**Comment by abhi-g** [comment]
If we end up making PRs to this repo, we'll request add.

**Comment by abhi-g** [comment]
Also, I'll need to force merge this PR, as owners file is not functional in current form

**Pull request merged**
