### PR TITLE
[MLMD] Final updates to lineage view

### PR DESCRIPTION
**Pull request by avdaredevil**
## About
Updated metadata to master upstream changes from [`kubeflow/frontend`](https://github.com/kubeflow/frontend), refactored imports
- This is the prereq change before I upstream element updates from [`kubeflow/pipelines`](https://github.com/kubeflow/pipelines) that are not part of the shared elements

### Meta
/area metadata
/area front-end
/priority p0
/assign @avdaredevil
/cc @kwasi @jlewi

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/metadata/216)

### CODE REVIEW

**Comment by avdaredevil** [comment]
Errors seem irrelevant:
image

**Comment by kwasi** [comment]
Looks good!

/lgtm
/approve

**Comment by avdaredevil** [comment]
The same issue again, merging...
image

**Pull request merged**
